name: geopy2020b
channels:
  - conda-forge
  - defaults
dependencies:
  - rasterio
  - h5py
  - poppler
  - ipython
  - mapclassify
  - requests
  - python[version='>=3.7']
  - cartopy
  - sphinx_rtd_theme
  - folium
  - xlwt
  - shapely[version='>=1.6']
  - geoviews
  - geojson
  - geos
  - jupyter_client
  - h5netcdf
  - ipykernel
  - networkx
  - openpyxl
  - pandas
  - pillow[version='>=5.2']
  - sphinx=2
  - gdal
  - pyproj
  - ipywidgets
  - geopy
  - numpy
  - jupyter
  - descartes
  - geoplot
  - statsmodels
  - rasterstats[version='>=0.13']
  - xlrd
  - matplotlib
  - toolz
  - sphinxcontrib
  - seaborn
  - geopandas[version='>=0.5']
  - geographiclib
  - pysal[version='>=2']
  - urllib3
  - netcdf4
  - owslib
  - rtree
  - fiona[version='>=1.8']
  - proj4
  - scikit-learn
  - scipy
  - pyarrow
  - ipython-sql
  - jupyterlab
  - pyodbc
  - pykrige
  - gstools
  - pytables
  - sympy
