name: geopy2020
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.18.0
  - dask=2.28.0
  - dask-core=2.28.0
  - datashader=0.11.1
  - descartes=1.1.0
  - earthpy=0.9.2
  - esda=2.3.1
  - fiona=1.8.17
  - folium=0.11.0
  - gdal=3.1.2
  - geographiclib=1.50
  - geojson=2.5.0
  - geopandas=0.8.1
  - geoplot=0.4.1
  - geopy=2.0.0
  - geos=3.8.1
  - geoviews=1.8.2
  - hdf4=4.2.13
  - hdf5=1.10.6
  - holoviews=1.13.4
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipywidgets=7.5.1
  - jupyter=1.0.0
  - jupyterlab=2.2.8
  - mapclassify=2.3.0
  - matplotlib=3.3.2
  - netcdf4=1.5.4
  - networkx=2.5
  - notebook=6.1.4
  - numpy=1.19.1
  - osmnx=0.16.0
  - owslib=0.20.0
  - pandas=1.1.2
  - pillow=7.2.0
  - proj=7.1.0
  - pyproj=2.6.1.post1
  - pysal=2.3.0
  - pytables=3.6.1
  - python=3.7.9
  - rasterio=1.1.6
  - rasterstats=0.14.0
  - requests=2.24.0
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - shapely=1.7.1
  - urllib3=1.24.3
